# Generated by Django 3.2 on 2023-06-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.Field(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('reviews_quantity', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
    ]
